### ISSUE TITLE
Installation failes

### ISSUE THREAD

**Issue by petjek** [ordnung/Speedport-Hybrid-Rebooter#1]
Hi,
just downloaded the script and followed the installation instructions. Installation of PyCrypto is terminated due to an error:

> src/pycrypto_common.h:27:20: fatal error: Python.h: Datei oder Verzeichnis nicht gefunden
> compilation terminated.
> error: command 'gcc' failed with exit status 1

Running a Raspberry 2 with actual Raspbian updated and upgraded.
Any idea pls?

Best,
petjek

**Comment by ghost** [comment]
Try to install python:

`sudo apt-get install python2.7-dev`

**Comment by faktor73** [comment]
Just for finalize the issue ... the installation of python-dev packages is the solution on Raspbian and also on Cubian (Cubieboard/Cubietruck) ARM-systems.
